
CHARACTERS = [
    "Super Mario",
    "Sonic the Hedgehog",
    "Pac-Man",
    "Donkey Kong",
    "Bowser",
    "Mario",
    "Luigi",
    "Peach",
    "Yoshi",
    "Wario",
    "Link",
    "Zelda",
    "Kirby",
    "Pikachu",
    "Samus Aran",
    "Fox McCloud",
    "Master Chief",
    "Doomguy",
    "Gordon Freeman",
    "Elvis Presley",
    "Michael Jackson",
    "Madonna",
    "Prince",
    "Bob Marley",
    "John Lennon",
    "Jimi Hendrix",
    "Elton John",
    "David Bowie",
    "Freddie Mercury",
    "Santa Claus",
    "the Easter Bunny",
    "the Tooth Fairy",
    "Cupcake Man",
    "Pizza Face",
    "Hot Dog Man",
    "Ice Cream Cone",
    "Chocolate Donut",
    "Cookie Monster",
    "the Gingerbread Man",
    "the Abominable Snowman",
    "the Loch Ness Monster",
    "Bigfoot",
    "the Kraken",
    "the Mummy",
    "the Werewolf",
    "Dracula",
    "the Frankenstein Monster",
    "the Invisible Man",
    "the Phantom of the Opera",
    "the Mothman",
    "the Chupacabra",
    "the yeti",
    "the sasquatch",
    "the jackalope",
    "the Jersey Devil",
    "the kraken",
    "the thunderbird",
    "the banshee",
    "the leprechaun",
    "the centaur",
    "the minotaur",
    "the griffin",
    "the unicorn",
    "the pegasus",
    "Pepe the Frog",
    "Doge",
    "Grumpy Cat",
    "Nyan Cat",
    "Bad Luck Brian",
    "Success Kid",
    "Socially Awkward Penguin",
    "Overly Attached Girlfriend",
    "Good Guy Greg",
    "Philosoraptor",
    "Forever Alone",
    "Scumbag Steve",
    "Chemistry Cat",
    "Skeptical Third World Kid",
    "Awkward Moment Seal",
    "Stoner Dog",
    "Sarcasm Bear",
    "Y U NO Guy",
    "Creepy Wonka",
    "Art Student Owl",
    "First World Problems",
    "WTF Face",
    "Trollface",
    "LOL Face",
    "Me Gusta",
    "Okay Guy",
    "Poker Face",
    "Facepalm",
    "Derp",
    "Forever Resentful Mother",
    "Angry School Boy",
    "White Trash Party",
    "Wojak",
    "Kermit the Frog",
    "Yawning Baby",
    "Roll Safe",
    "Ermahgerd",
    "Annoyed Picard",
    "Stoner Dog",
    "Salt Bae",
    "Lenny Face",
    "Fap Guy",
    "Pepe Hands",
]
    

LOCATIONS = [
    "in a luna park",
    "on a beach",
    "in a forest",
    "on a mountain",
    "in a city",
    "in a desert",
    "in a cave",
    "on a planet",
    "in a castle",
    "on a boat",
    "in space",
    "underwater",
    "in a castle",
    "in a laboratory",
    "in a castle",
    "in a toy store",
    "in a museum",
    "in a zoo",
    "in a library",
    "on the moon",
    "on Mars",
    "on a comet",
    "in a black hole",
    "on a asteroid",
    "in a parallel universe",
    "in a alternate dimension",
    "at a rock concert",
    "in front of the Colosseum",
    "at the stadium",
    "at a sports game",
    "at the circus",
    "at the carnival",
    "at a parade",
    "at a concert",
    "at a music festival",
    "at a theater",
    "at a movie theater",
    "at a comedy club",
    "at a magic show",
    "at a fair",
    "at a amusement park",
    "at a pool party",
    "at a beach party",
    "at a barbecue",
    "at a picnic",
    "at a dinner party",
    "at a wedding",
    "at a funeral",
    "at a wake",
    "at the Great Pyramid of Giza",
    "at the Eiffel Tower",
    "at the Taj Mahal",
    "at the Colosseum",
    "at the Great Wall of China",
    "at the Christ the Redeemer statue",
    "at the Sydney Opera House",
    "at the Statue of Liberty",
    "at the Machu Picchu",
    "at the Leaning Tower of Pisa",
    "at the Big Ben",
    "at the Louvre Museum",
    "at the Notre Dame Cathedral",
    "at the Stonehenge",
    "at the Chichen Itza",
    "at the Great Sphinx of Giza",
    "at the Pyramids of Teotihuacan",
    "at the Lascaux Cave Paintings",
    "at the Angkor Wat",
    "at the Temple of Artemis",
    "at the Mount Rushmore National Memorial",
    "at the St. Peter's Basilica",
    "at the Mount Fuji",
    "at the Grand Canyon",
    "at the Buckingham Palace",
    "at the Kremlin",
    "at the Times Square",
    "at the Central Park",
    "at the Disney World",
    "at the Niagara Falls",
    "at the Yellowstone National Park",
    "at the Grand Bazaar",
    "at the Forbidden City",
    "at the Burj Khalifa",
    "at the Petronas Twin Towers",
    "at the Red Square",
    "at the Berlin Wall",
    "at the Neuschwanstein Castle",
]


STYLES = [
    "a painting by Salvatore Dalì",
    "a sculpture by Michelangelo",
    "a drawing by Leonardo da Vinci",
    "a photograph by Ansel Adams",
    "a collage by Pablo Picasso",
    "a collage by Banksy",
    "a drawing by Van Gogh",
    "a sculpture by Rodin",
    "a painting by Monet",
    "a photograph by Annie Leibovitz",
    "a mosaic by Marc Chagall",
    "a watercolor by Georgia O'Keeffe",
    "a collage by Henri Matisse",
    "a painting by Frida Kahlo",
    "a drawing by Rembrandt",
    "a photograph by Diane Arbus",
    "a sculpture by Henry Moore",
    "a painting by Jackson Pollock",
    "a photograph by Robert Frank",
    "a sculpture by Alexander Calder",
    "a painting by Claude Monet",
    "a drawing by Edgar Degas",
    "a photograph by Dorothea Lange",
    "a painting by Vincent Van Gogh",
    "a photograph by Richard Avedon",
    "a drawing by John Singer Sargent",
    "a sculpture by Constantin Brâncuși",
    "a painting by Pierre-Auguste Renoir",
    "a photograph by Yousuf Karsh",
    "a drawing by Toulouse-Lautrec",
    "a sculpture by Barbara Hepworth",
    "a painting by Rembrandt",
    "a photograph by Cindy Sherman",
    "a drawing by Egon Schiele",
    "a sculpture by Isamu Noguchi",
    "a painting by Diego Rivera",
    "a photograph by Walker Evans",
    "a drawing by John Constable",
    "a sculpture by Auguste Rodin",
    "a painting by Paul Cézanne",
    "a photograph by Ansel Adams",
    "a drawing by Henri de Toulouse-Lautrec",
    "a sculpture by David Smith",
    "a painting by Gustav Klimt",
    "a photograph by Edward Weston",
    "a drawing by Gustav Klimt",
    "a sculpture by Alberto Giacometti",
    "a painting by Paul Gauguin",
    "a photograph by Weegee",
    "a drawing by Raphael",
    "a sculpture by Constantin Brâncuși",
    "a painting by Henri Matisse",
    "a photograph by Henri Cartier-Bresson",
    "a drawing by Albrecht Dürer",
    "a sculpture by Henry Moore",
    "a painting by Frans Hals",
    "a photograph by Alfred Stieglitz",
    "a drawing by Francisco Goya",
    "a sculpture by Antoine Bourdelle",
    "a painting by Jan Vermeer",
    "a photograph by Dorothea Lange",
    "Hyper-Realistic",
    "Cyberpunk",
    "Extremely detailed",
    "Intrinsic details",
    "Realistic",
    "Detailed",
    "Finely detailed",
    "Highly detailed",
    "Extraordinary detail",
    "Intricate details",
    "Extraordinary realism",
    "Extraordinary detail",
    "Super-realistic",
    "Extraordinary detail and realism",
    "Exceptional realism",
    "Incredible detail",
    "Extraordinary realism and detail",
    "Incredibly detailed",
    "Extraordinary level of detail",
    "Remarkable detail",
    "Incredible realism",
    "Extraordinary level of realism",
    "Exceptional level of detail",
    "Superb realism",
    "Exceptional level of realism",
    "Incredible level of detail",
    "Superb detail",
    "Extraordinary level of detail and realism",
    "Exceptional level of detail and realism",
    "Incredible level of detail and realism",
    "Superb level of detail",
    "Extraordinary level of detail and realism",
    "Exceptional level of detail and realism",
    "Incredible level of detail and realism",
    "Superb level of detail and realism",
    "Extraordinary level of detail and realism",
    "Exceptional level of detail and realism",
    "Incredible level of detail and realism",
    "Life-like",
    "Ultra-realistic",
    "Realistic-looking",
    "Lifelike",
    "Incredibly realistic",
    "Exceptionally detailed",
    "Unbelievable detail",
    "Exceptional level of realism",
    "Extraordinary level of detail and realism",
    "Realistic-like",
    "Ultra-detailed",
    "Realistic-like",
    "Exceptionally realistic",
    "Super-detailed",
    "Remarkably realistic",
    "Realistic-like",
    "Exceptionally realistic",
    "Super-detailed",
    "Extraordinarily realistic",
    "Superb level of detail and realism",
    "Exceptionally detailed",
    "Extraordinarily detailed",
    "Ultra-realistic",
    "Extraordinarily realistic",
    "Extraordinarily detailed",
]
